#!/usr/bin/env ruby

require_relative 'git_utils.rb'

exit_if_on_the_master_branch

`git a`

puts "Enter a commit comment..."
branch_name = readline.chomp.strip.gsub(" ","_").downcase

def commit(branch_name)
  `git ci #{branch_name}`
end


if (branch_name != "")
  commit(branch_name)
  `git push origin`
end

`git commit -m "no message"`
`git push origin`



new change